=== srivasta/QMS/Instrumentation/Probes/Continuous/Simple/FFD/ffdProbe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- *****************************************************************
 *** Copyright (c) 2001, System/Technology Development Corporation .
 ***                
 *** Filename:      ffdProbe.xsd
 *** Version:       1.0
 *** Description:   Schema Description for the Fast Failure Detector Probe
 ***                
 *** Author:        Amarendranath Vadlamudi <amar.vadlamudi@stdc.com>
 *** Created at:    Mon Sep 24 20:17:55 2001
 *** Modified by:   Amarendranath Vadlamudi <nath@vedam>
 *** Modified at:   Fri Dec  7 20:26:38 2001
 *** Status:        Experimental, do not distribute.
 *** Update count:  4
 ***************************************************************** -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.stdc.com/2001/QMS/Probes/Continuous/FFDProbe"
  targetNamespace="http://www.stdc.com/2001/QMS/Probes/Continuous/FFDProbe"
  elementFormDefault="qualified"
  version="$Id: ffdProbe.xsd,v 1.2 2001/12/10 21:30:51 nath Exp $" >
  
  <xsd:simpleType name="ipv4AddressType">
    <xsd:annotation>
      <xsd:documentation>
	Datatype for representing IP addresses.  Examples,
	129.83.64.255, 64.128.2.71, etc.
	This datatype restricts each field of the IP address
	to have a value between zero and 255, i.e.,
	[0-255].[0-255].[0-255].[0-255]
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="((1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9]?[0-9]|2[0-4][0-9]|25[0-5])"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="FFDVersionType">
    <xsd:restriction base="xsd:positiveInteger">
      <xsd:minInclusive value="1"/>
      <xsd:maxInclusive value="1"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="FFDStatusType">
    <xsd:annotation>
      <xsd:documentation>
	Host status is either "up" or "down".
      </xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="up"/>
      <xsd:enumeration value="down"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:element name="ffd_host" type="ipv4AddressType">
    <xsd:annotation>
      <xsd:documentation>
	The IP address of the host that the FFD Instance is running
	on.
      </xsd:documentation>
    </xsd:annotation>
  </xsd:element>

  <xsd:element name="ffd_instance" type="xsd:string">
    <xsd:annotation>
      <xsd:documentation>
	The instance of the FFD that is producing this report.
      </xsd:documentation>
    </xsd:annotation>
  </xsd:element>

  <xsd:element name="ffd_host_down">
    <xsd:annotation>
      <xsd:documentation>
	The "host down" message from FFD. This message contains the
	FFD version number, the host IPv4 address and the time
	expressed as a decimal number, which is the number of seconds
	since Unix Epoch.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element name="version" type="FFDVersionType"/>
	<xsd:element name="host_ip" type="ipv4AddressType"/>
	<xsd:element name="time" type="xsd:decimal"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ffd_host_status_change">
    <xsd:annotation>
      <xsd:documentation>
	The "host status" message that is periodic, containing
	version, host IPv4 address, the state of a set of hosts, host
	jitter measure and the time in seconds since Unix Epoch.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element name="version" type="FFDVersionType"/>
	<xsd:element name="host_ip" type="ipv4AddressType"/>
	<xsd:element name="host_state" type="FFDStatusType"/>
	<xsd:element name="host_jitter" type="xsd:decimal"/>
	<xsd:element name="time" type="xsd:decimal"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ffd_config">
    <xsd:annotation>
      <xsd:documentation>
	The current configuration of the FFD containing its version,
	the list of hosts it is watching, the interval it has been
	configured to report status at and the time since
	Epoch.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element name="version" type="FFDVersionType"/>
	<xsd:element name="host_list">
	  <xsd:complexType>
	    <xsd:sequence maxOccurs="unbounded">
	      <xsd:element name="host_ip" type="ipv4AddressType"/>
	      <xsd:element name="host_state" type="FFDStatusType"/>
	    </xsd:sequence>
	  </xsd:complexType>
	</xsd:element>
	<xsd:element name="reportInterval" type="xsd:decimal"/>
	<xsd:element name="time" type="xsd:decimal"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>


  <xsd:element name="ffd_message">
    <xsd:annotation>
      <xsd:documentation>
	The message can be of three types.
	1 - A Host Down message
	2 - A Host Status Message
	3 - FFD Configuration Message
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:choice>
	<xsd:element ref="ffd_host_down"/>
	<xsd:element ref="ffd_host_status_change"/>
	<xsd:element ref="ffd_config"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="ffd_report">
    <xsd:annotation>
      <xsd:documentation>
	This will be the standard format for FFD Reports to QMS
      </xsd:documentation>
    </xsd:annotation>
    <xsd:complexType>
      <xsd:sequence>
	<xsd:element ref="ffd_host"/>
	<xsd:element ref="ffd_instance"/>
	<xsd:element ref="ffd_message"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="probeCommandType">
    <xsd:annotation>
      <xsd:documentation>The FFD probe supports a set of control
        strings that allows the requestor to control the function of
        the probe. The supported actions are "start", "stop", "pause"
        and "resume". Corresponding to these control actions, the
        probe executes the action.
      </xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="action">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="start"/>
            <xsd:enumeration value="stop"/>
            <xsd:enumeration value="pause"/>
            <xsd:enumeration value="resume"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="ffdProbe">
    <xsd:complexType>
      <xsd:choice>
	<xsd:element name="probeControl" type="probeCommandType"/>
	<xsd:element ref="ffd_report"/>
      </xsd:choice>
    </xsd:complexType>
  </xsd:element>

</xsd:schema>

=== srivasta/QMS/Instrumentation/Probes/Continuous/Simple/FFD/test/ffdProbe_Response_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- *****************************************************************
 *** Copyright (c) 2001, System/Technology Development Corporation .
 ***                
 *** Filename:      ffdProbe_Response_2.xml
 *** Version:       1.0
 *** Description:   Sample XML File
 ***                
 *** Author:        Amarendranath Vadlamudi <nath@vedam>
 *** Created at:    Fri Dec  7 20:27:59 2001
 *** Modified by:   Amarendranath Vadlamudi <nath@vedam>
 *** Modified at:   Fri Dec  7 20:37:19 2001
 *** Status:        Experimental, do not distribute.
 *** Update count:  3
 ***************************************************************** -->

<!-- This is a sample XML file that is useful to test any parser that -->
<!-- uses the ffdProbe.xsd schema defined for the Fast Failure Detector -->
<!-- Continuous Probe -->


<ffdProbe xmlns="http://www.stdc.com/2001/QMS/Probes/Continuous/FFDProbe"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.stdc.com/2001/QMS/Probes/Continuous/FFDProbe 
  ffdProbe.xsd">
  <ffd_report>
    <ffd_host>130.105.2.32</ffd_host>
    <ffd_instance>FFD</ffd_instance>
    <ffd_message>
      <ffd_host_status_change>
	<version>1</version>
	<host_ip>130.105.2.32</host_ip>
	<host_state>down</host_state>
	<host_jitter>2.654</host_jitter>
	<time>999811615.704724</time>
      </ffd_host_status_change>
    </ffd_message>
  </ffd_report>
</ffdProbe>

=== srivasta/QMS/Instrumentation/Probes/Continuous/Simple/FFD/test/ffdProbe_Response_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- *****************************************************************
 *** Copyright (c) 2001, System/Technology Development Corporation .
 ***                
 *** Filename:      ffdProbe_Response_3.xml
 *** Version:       1.0
 *** Description:   Sample XML File
 ***                
 *** Author:        Amarendranath Vadlamudi <nath@vedam>
 *** Created at:    Fri Dec  7 20:27:59 2001
 *** Modified by:   Amarendranath Vadlamudi <nath@vedam>
 *** Modified at:   Fri Dec  7 20:38:18 2001
 *** Status:        Experimental, do not distribute.
 *** Update count:  6
 ***************************************************************** -->

<!-- This is a sample XML file that is useful to test any parser that -->
<!-- uses the ffdProbe.xsd schema defined for the Fast Failure Detector -->
<!-- Continuous Probe -->


<ffdProbe xmlns="http://www.stdc.com/2001/QMS/Probes/Continuous/FFDProbe"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.stdc.com/2001/QMS/Probes/Continuous/FFDProbe 
  ffdProbe.xsd">
  <ffd_report>
    <ffd_host>130.105.2.32</ffd_host>
    <ffd_instance>FFD</ffd_instance>
    <ffd_message>
      <ffd_config>
	<version>1</version>
	<host_list>
	  <host_ip>130.105.2.32</host_ip>
	  <host_state>up</host_state>
	  <host_ip>130.105.2.33</host_ip>
	  <host_state>down</host_state>
	  <host_ip>130.105.2.34</host_ip>
	  <host_state>up</host_state>
	  <host_ip>130.105.2.35</host_ip>
	  <host_state>down</host_state>
	</host_list>
	<reportInterval>25.045231</reportInterval>
	<time>999811615.704724</time>
      </ffd_config>
    </ffd_message>
  </ffd_report>
  
</ffdProbe>
